local set = vim.keymap.set
vim.g.mapleader = " "

-- <-2<CR> (move selection up one line)
-- gv (re select selection)
-- = (re indent selection)
-- gv (re select selection)
set("v", "K", ":m '<-2<CR>gv=gv")
set("v", "J", ":m '>+1<CR>gv=gv")
set("n", "K", ":m -2<CR>==")
set("n", "J", ":m +1<CR>==")
set("n", "<M-j>", "<CMD>wincmd j<CR>")
set("n", "<M-k>", "<CMD>wincmd k<CR>")
set("n", "<M-h>", "<CMD>wincmd h<CR>")
set("n", "<M-l>", "<CMD>wincmd l<CR>")
set("n", "<leader><leader>x", "<CMD>source %<CR>", { desc = "Source the current file" })
set("n", "<leader>x", ":.lua<CR>", { desc = "Execute line" })
set("v", "<leader>x", ":lua<CR>", { desc = "Execute selection" })
set("n", "<C-n>", "<CMD>cnext<CR>")
set("n", "<C-p>", "<CMD>cprev<CR>")
set("n", "<C-c>", "<CMD>cclose<CR>")
set("n", "<leader>h", "<CMD>bp<CR>", { desc = "Previous buffer" })
set("n", "<leader>l", "<CMD>bn<CR>", { desc = "Next buffer" })
set("n", "<leader>q", "<CMD>bd<CR>", { desc = "Close buffer" })
set("n", "<M-=>", "<CMD>resize +1<CR>")
set("n", "<M-->", "<CMD>resize -1<CR>")
set("n", "<M-.>", "<CMD>vertical resize +1<CR>")
set("n", "<M-,>", "<CMD>vertical resize -1<CR>")
